update git hooks

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -12,11 +12,10 @@ fi
 
 if [ $branchName == 'develop' ]
 then
-  echo -e "\n🚫 Cannot push to remote develop branch, please create your own branch and use PR."
+  echo -e "\n🚫 Cannot commit to remote develop branch, please create your own branch with develop/branch-name format" && exit 1
 fi
 
 echo -e ">> Finish checking branch name.\n==="
-echo -e ">> Pushing to $branchName\n==="
 
 npm run lint
 npm run test
